name: chat_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0

  #for firebase authentication
  firebase_auth: ^4.14.0

  #for google sign in
  google_sign_in: ^6.1.6

  cloud_firestore: ^4.13.2

  cached_network_image: ^3.3.0

  #for accessing firebase storage
  firebase_storage: ^11.5.2

  #for picking Emojis
  emoji_picker_flutter: ^1.6.3

  #for picking images
  image_picker: ^1.0.4

  #for calling REST APIs
  http: 

  #for creating notification channel
  flutter_notification_channel: ^2.0.0

  #for saving images to gallery
  gallery_saver: ^2.3.2


  #for accessing firebase notifications
  firebase_messaging: ^14.7.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  fonts:
    - family: Raleway
      fonts:
        
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
          
    
 