// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzD9mCMy8Em_6rTQ2MYg44wMHIDf7Irqk',
    appId: '1:990443201962:web:cc0d7040d34c52aef677d3',
    messagingSenderId: '990443201962',
    projectId: 'chat-app-e47aa',
    authDomain: 'chat-app-e47aa.firebaseapp.com',
    storageBucket: 'chat-app-e47aa.appspot.com',
    measurementId: 'G-9NT4E8NC5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQAf3q_kHNSXSIv4Le1BRGSX-0_5aCQ4',
    appId: '1:990443201962:android:70bd6a7399254a9ef677d3',
    messagingSenderId: '990443201962',
    projectId: 'chat-app-e47aa',
    storageBucket: 'chat-app-e47aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFyNyOscK0ADnWgv2j4DoRmMSLXyf90U',
    appId: '1:990443201962:ios:db1d4c5ad7d53221f677d3',
    messagingSenderId: '990443201962',
    projectId: 'chat-app-e47aa',
    storageBucket: 'chat-app-e47aa.appspot.com',
    androidClientId: '990443201962-6hp780t21j86nu06fk8anqivk79q59bl.apps.googleusercontent.com',
    iosClientId: '990443201962-ubvhbikunlhs4t8g24fl8ll2f5bpqlsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFyNyOscK0ADnWgv2j4DoRmMSLXyf90U',
    appId: '1:990443201962:ios:11d4356478d5650cf677d3',
    messagingSenderId: '990443201962',
    projectId: 'chat-app-e47aa',
    storageBucket: 'chat-app-e47aa.appspot.com',
    androidClientId: '990443201962-6hp780t21j86nu06fk8anqivk79q59bl.apps.googleusercontent.com',
    iosClientId: '990443201962-nuknu06dan8h3hv3ica2fsi8jghenf3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
